### ISSUE TITLE
[REQUEST] Collection of Language CFs for Sonarr v4

### ISSUE THREAD

**Issue by owine** [TRaSH-/Guides#1015]
**For which application would like to see this Guide ?**
Sonarr v4

**Describe what you would like to see in the Tutorial/Guide**
A collection of language CFs and suggested scoring to guide users through setting up language preferences.

**Comment by TRaSH-** [comment]
Work in Progress

**Comment by TRaSH-** [comment]
Bump, so it doesn't get closed
