### ISSUE TITLE
[Bug] Missing Anime Quality Definitions

### ISSUE THREAD

**Issue by MetalNeo** [TRaSH-/Guides#1031]
**Which Guide**
Quality Settings (File Size) for Radarr: https://trash-guides.info/Radarr/Radarr-Quality-Settings-File-Size

**Describe the Error in the Guide**
The quality definitions only go to HDTV-720p, but the Anime Quality Profiles include references to definitions such as DVD which are not included here.

**Expected behavior**
Quality definitions for the referenced Anime Quality Profiles, perhaps in a second section similar to the Sonarr section.

**Screenshots**
N/A

**Comment by TRaSH-** [comment]
@FonduemangVI 
perhaps add them to the Radarr Anime guide if they aren't the default one

**Comment by FonduemangVI** [comment]
> @FonduemangVI perhaps add them to the Radarr Anime guide if they aren't the default one

I'll take a look

**Comment by FonduemangVI** [comment]
The definitions aren't missing we are just using the existing Radarr ones that the normal guide uses
