### ISSUE TITLE
[Bug] SiCFoI not being picked up as HDR

### ISSUE THREAD

**Issue by RZeroX2** [TRaSH-/Guides#1032]
**Which Guide**
Sonarr

**Describe the Error in the Guide**
SiCFoI does not include HDR in the release name so it's not being picked up as HDR
Tom.Clancys.Jack.Ryan.S02E07.2160p.UHD.BluRay.Remux.HEVC.TrueHD.7.1.Atmos-SiCFoI

**Expected behavior**
For it to be picked up as HDR even where the release name doesn't mention it

**Comment by TRaSH-** [comment]
Hmm, need to check if that's the case with all their releases, like framestor does

**Comment by RZeroX2** [comment]
> Hmm, need to check if that's the case with all their releases, like framestor does.
> 
> Which Sonarr version are you running ?

4.0.0.281

**Comment by TRaSH-** [comment]
@FonduemangVI I think you do remuxes for Sonarr don't you ?

**Comment by FonduemangVI** [comment]
> @FonduemangVI I think you do remuxes for Sonarr don't you ?

Yep I did them. Let me take a look

**Comment by FonduemangVI** [comment]
@TRaSH- just did some research it looks like SICFoI doesn't include HDR in their naming but their 4k remuxes do have HDR

**Comment by RZeroX2** [comment]
Tried it again using the updated custom format for HDR but it doesn't seem to be working as I can't see any score being assigned to it but HDR (undefined) seems to be working fine and also SDR custom format seems to be missing SiCFoI

**Comment by TRaSH-** [comment]
It should be recognized as HDR undefined and not as HDR
After import it will recornize the correct HDR metadata
Good catch for the SDR
I will ask someone to add them ASAP being I'm already at my work and don't want to do this on my phone.

**Comment by RZeroX2** [comment]
> It should be recognized as HDR undefined and not as HDR After import it will recornize the correct HDR metadata Good catch for the SDR I will ask someone to add them ASAP being I'm already at my work and don't want to do this on my phone.

Well in that case everything seems to be working fine when it comes the HDR custom format also thanks for getting this issue fixed.

**Comment by FonduemangVI** [comment]
> .

Glad to hear it's working. Sorry I missed the SDR I'll get it added shortly.
