### ISSUE TITLE
[Bug] Sonarr TrueHD and TrueHD Atmos custom formats not mutually exclusive

### ISSUE THREAD

**Issue by EdLaughton** [TRaSH-/Guides#1038]
**Which Guide**
Sonarr SQP

**Describe the Error in the Guide**
Sonarr show can have both the TrueHD custom format and the TrueHD Atmos custom format.

**Expected behavior**
Should only have one of these.

**Additional context**
TrueHD custom format negated atmos is:
`\bATMOS(\b|\d)`
while TrueHD Atmos custom format atmos is:
`\b(ATMOS|CtrlHD|W4NK3R|DON)(\b|\d)`

therefore if CtrlHD|W4NK3R|DON and not also ATMOS then it will have both the TrueHD and TrueHD Atmos custom formats applied which can overscore that particular release quite majorly.

**Fix**
For TrueHD negate Atmos the same as for TrueHD Atmos e.g. `\b(ATMOS|CtrlHD|W4NK3R|DON)(\b|\d)`

**Comment by TRaSH-** [comment]
> **Which Guide** Sonarr SQP
> 
> **Describe the Error in the Guide** Sonarr show can have both the TrueHD custom format and the TrueHD Atmos custom format.
> 
> **Expected behavior** Should only have one of these.
> 
> **Additional context** TrueHD custom format negated atmos is: `\bATMOS(\b|\d)` while TrueHD Atmos custom format atmos is: `\b(ATMOS|CtrlHD|W4NK3R|DON)(\b|\d)`
> 
> therefore if CtrlHD|W4NK3R|DON and not also ATMOS then it will have both the TrueHD and TrueHD Atmos custom formats applied which can overscore that particular release quite majorly.
> 
> **Fix** For TrueHD negate Atmos the same as for TrueHD Atmos e.g. `\b(ATMOS|CtrlHD|W4NK3R|DON)(\b|\d)`

There is no SQP for Sonarr to start with

But we use this with Radarr with success.
Do you have actual examples that I can look at and test?
I'm not yet at home to do research my self.

**Comment by EdLaughton** [comment]
Sure - so:
`Show.Title.S#E#.Episode.Title.2160p.UHD.BluRay.TrueHD.7.1.DoVi.x265-DON`
gives me the custom formats with scores (at least for my settings) of:
- TrueHD Atmos (3000)
- TrueHD (3000)
- DV (1500)

happy to share my Recylarr .yml file for Sonarr if needed.

**Comment by TRaSH-** [comment]
hmm, i think i know what you mean, i just compared the 2 CF json and the Sonarr one is missing the rlsgrp that Radarr has,
Think I removed them being the guide only covers webdl en nothing else (for the time being)
But i will make them identical
Thnx

**Comment by EdLaughton** [comment]
Great sounds good. Appreciate I am probably using it outside of what has been figured out so far with the Sonarr v4 custom formats.

My other question would be for the `HD Bluray Tier 01` and `HD Bluray Tier 02` would it be possible to either duplicate for UHD or remove `Not 2160p`?

Using the same example as above, DON is Tier 01, but because it is 2160p that custom format doesn't apply.

**Comment by yammes08** [comment]
> Great sounds good. Appreciate I am probably using it outside of what has been figured out so far with the Sonarr v4 custom formats.
> 
> My other question would be for the `HD Bluray Tier 01` and `HD Bluray Tier 02` would it be possible to either duplicate for UHD or remove `Not 2160p`?
> 
> Using the same example as above, DON is Tier 01, but because it is 2160p that custom format doesn't apply.

There are separate UHD Tiers for Radarr (as different groups do them, although some do both), and I don't believe these have been made yet for Sonarr. I expect that'll be a future change/addition.

**Comment by TRaSH-** [comment]
> My other question would be for the `HD Bluray Tier 01` and `HD Bluray Tier 02` would it be possible to either duplicate for UHD or remove `Not 2160p`?
> 
> Using the same example as above, DON is Tier 01, but because it is 2160p that custom format doesn't apply.

No we won't remove the Not 2160p because some rlsgrps can do a great job on 1080p but suck at 2160p or the other way around.

That's why we have a separate HD-, UHD-Encodes and Remuxes.

Being for TV shows that WEBDL is the sweetspot and minimal difference with most TV shows we never covered anything else with Sonarr.

We recently started to do tests and start collecting information for Remuxes and Encodes.
But with encodes it's still in most cases minimal difference between the WEBDL

**Comment by TRaSH-** [comment]
@EdLaughton if you want to help to collect creditable RlsGrp that do 

- Remuxes
- HD Blurays 
- UHD Blurays

Perhaps you want to join our discord to help out,
We've a dedicated private test channel for this.
