### ISSUE TITLE
[Bug][Radarr] - Issue downloading torrent version

### ISSUE THREAD

**Issue by cojo1989** [TRaSH-/Guides#1093]
**Which Guide**
Please add which Guide you found a Bug/Error with.
Radarr custom format / unRaid linux docker radarr

**Describe the Error in the Guide**
So I followed the guide made by you, very nice, spot on. But for some reason even if is set up -10000 for 3D still downloading the 3D one and is ignoring other verions.

**Expected behavior**
I was expecting when you set up -10000 on some of the format to ignore them (do not download them.)

**Screenshots**
![image](https://user-images.githubusercontent.com/36346905/212335034-ad182f40-9b3b-4187-9bc0-df59f25fd006.png)
![image](https://user-images.githubusercontent.com/36346905/212335112-37f09f90-5f0c-483b-a254-4689d608cd25.png)
![image](https://user-images.githubusercontent.com/36346905/212335155-a1985bfc-1ad7-43cb-9a05-aa0acfdfdc5a.png)

**Additional context**
N/A

Is something I do wrong or what is the issue if you can help me.
Thank you.

**Comment by cojo1989** [comment]
Issue is I don`t want 3D, i want to ignore that release. I never downloaded that version plus I don`t have a 3D tv.
It is negative 8500 (-8500).

**Comment by bakerboy448** [comment]
> Issue is I don't want 3D, i want to ignore that release. I never downloaded that version plus I don't have a 3D tv.
> 
> It is negative 8500 (-8500).

The release is ignored if you follow the guide.  There's nothing wrong, no issue, and no action to take.

You or someone with access to your Radarr either grabbed it manually or it was grabbed prior to your configuration of the 3D custom format and the quality profile. The screenshot confirms it would be rejected today, so what you want already exits.

**Comment by cojo1989** [comment]
> > Issue is I don't want 3D, i want to ignore that release. I never downloaded that version plus I don't have a 3D tv.
> > It is negative 8500 (-8500).
> 
> The release is ignored if you follow the guide. There's nothing wrong, no issue, and no action to take.
> 
> You or someone with access to your Radarr either grabbed it manually or it was grabbed prior to your configuration of the 3D custom format and the quality profile. The screenshot confirms it would be rejected today, so what you want already exits.

Okay, I will observe it more, in case I will need help I will come back. Anyway great guide, thank you for your help and confirming everything is okay. Appreciate.

**Comment by TRaSH-** [comment]
Keep in mind a manual search shows everything it finds
This also include rejected ones and that's why it has a exclamation icon
