### ISSUE TITLE
[Bug] SABnzbd - Paths and Categories - nested incomplete

### ISSUE THREAD

**Issue by thezoggy** [TRaSH-/Guides#1106]
**Which Guide**
SABnzbd - Paths and Categories

**Describe the Error in the Guide**
It shows the incomplete folder being nested inside of the completed folder. 
`/data/usenet/incomplete-downloads` vs `/data/usenet`

**Expected behavior**
The incomplete folder should be adjacent to prevent issues if a script/app is processing the completed folder recursively.

**Screenshots**
For the context of that page it may just be easier to blur out incomplete folder since the context is showing the whole completed folder + category concept.

**Comment by TRaSH-** [comment]
Thnx will try to blur it this evening

**Comment by thezoggy** [comment]
one is not nested while one is. 
so if something was to process your example "/data.usenet" recursively, it would see the "/data/.usenet/incomplete" stuff as its nested within it. its recommended to have incomplete and complete adjacent of each other.

**Comment by TRaSH-** [comment]
/downloads/incomplete
/downloads/complete

/data/usenet/incomplete
/data/usenet/category-name

So the issue would only be if you don't use categories ?

**Comment by thezoggy** [comment]
Yes

As I noted on discord, it's not a huge deal because the content of that page is showing the whole let's do categories to segment stuff. If they follow the whole page then it's fine, it's just of course people doing half way or doing dumb things where there ends up being collisions.

**Comment by TRaSH-** [comment]
i will create a new screenshot, and change the instructions, to cover is correctly
