### ISSUE TITLE
[Sonarr] Updated naming scheme to be consistent with Radarr

### ISSUE THREAD

**Issue by TRaSH-** [TRaSH-/Guides#1116]
It doesn't work with the folder name either (the folder gets renamed to `Kingdom 2019 (2019)` as well. (I forgot to do the "move series trick to rename the series folder, that's why I thought it was inconsistent, PEBKAC).

At the end of the day, the issue is that `CleanTitle` is not a great entry to use as it may or may not already contain a year. To ensure that the year is there consistently, we should either use `CleanTitleYear` (but parenthesis are getting stripped) or `TitleYear` (but it isn't the clean version).

I've opened a ticket on Sonarr to put more context and potential improvements that could be made to handle this scenario:
https://github.com/Sonarr/Sonarr/issues/5369

_Originally posted by @ColinHebert in https://github.com/TRaSH-/Guides/issues/1088#issuecomment-1381720337_

Could you perhaps test the following
`{Series CleanTitleWithoutYear} ({Series Year})`

![image](https://user-images.githubusercontent.com/6155095/213941864-d7b7fe06-c9a8-47ec-8bfa-bd8e8cc89dc0.png)

**Comment by ColinHebert** [comment]
I am not yet running v4 (but was considering it about 10 mins ago), so the commit that introduces `CleanTitleWithoutYear` isn't available yet ( https://github.com/Sonarr/Sonarr/commit/3973571411b466a18d0ce6de828ed837683247ed )

**Comment by TRaSH-** [comment]
![image](https://user-images.githubusercontent.com/6155095/213942447-5de86a2b-abd2-493c-8cf0-de913877d43c.png)

**Comment by ColinHebert** [comment]
Sorry, took me a bit of time to circle back.

So in general, it works well. Only difference is that the previous version was the "non-clean" version of the title. So we'll see some renames (which I think is fine)

A handful of examples:

```diff
Naming pattern Series:{Series CleanTitleWithoutYear} ({Series Year}) - S{season:00}E{episode:00} - {Episode CleanTitle} [{Custom Formats }{Quality Full}]{[MediaInfo VideoDynamicRangeType]}{[Mediainfo AudioCodec}{ Mediainfo AudioChannels]}{[MediaInfo VideoCodec]}{-Release Group}
Naming pattern Anime: {Series CleanTitleWithoutYear} ({Series Year}) - S{season:00}E{episode:00} - {absolute:000} - {Episode CleanTitle} [{Custom Formats }{Quality Full}]{[MediaInfo VideoDynamicRangeType]}[{MediaInfo VideoBitDepth}bit]{[MediaInfo VideoCodec]}[{Mediainfo AudioCodec} { Mediainfo AudioChannels}]{MediaInfo AudioLanguages}{-Release Group}

- Season 01/Cautious Hero - The Hero Is Overpowered but Overly Cautious (2019) - S01E12 - 012 - The Hero Is Overpowered But Overly Cautious [Bluray-1080p][10bit][x264][FLAC 5.1][EN+JA]-NH.mkv
+ Season 01/Cautious Hero The Hero Is Overpowered but Overly Cautious (2019) - S01E12 - 012 - The Hero Is Overpowered But Overly Cautious [Bluray-1080p][10bit][x264][FLAC 5.1][EN+JA]-NH.mkv
...
- Specials/Re - ZERO, Starting Life in Another World (2016) - S00E17 - Re-PETIT 6 Greed That Isn't a Pig's [Bluray-1080p][Opus 2.0][x265]-Tenrai-Sensei.mkv
+ Specials/Re ZERO Starting Life in Another World (2016) - S00E17 - Re-PETIT 6 Greed That Isn't a Pig's [Bluray-1080p][Opus 2.0][x265]-Tenrai-Sensei.mkv
...
- Season 02/KonoSuba – God's blessing on this wonderful world!! (2016) - S02E05 - 015 - Servitude for This Masked Knight! [Bluray-1080p][10bit][x265][Opus 2.0]-Pog42.mkv
+ Season 02/KonoSuba – Gods blessing on this wonderful world!! (2016) - S02E05 - 015 - Servitude for This Masked Knight! [Bluray-1080p][10bit][x265][Opus 2.0]-Pog42.mkv
...
- Season 01/Cunk & Other Humans on 2019 (2019) - S01E03 - Episode 3 [HDTV-1080p][AC3 2.0][h264]-LiNKLE.mkv
+ Season 01/Cunk and Other Humans on 2019 (2019) - S01E03 - Episode 3 [HDTV-1080p][AC3 2.0][h264]-LiNKLE.mkv
```

**Comment by drrlvn** [comment]
This was closed automatically for some reason but does look like a good change to me.

**Comment by bakerboy448** [comment]
Believe this ended up getting fixed at some point given the naming

https://trash-guides.info/Sonarr/Sonarr-recommended-naming-scheme/#episode-format

**Comment by bakerboy448** [comment]
Believe this ended up getting fixed at some point given the naming

https://trash-guides.info/Sonarr/Sonarr-recommended-naming-scheme/#episode-format

**Comment by drrlvn** [comment]
I might be missing something but the guide you linked still uses `{Series TitleYear}` and not `{Series CleanTitleWithoutYear} ({Series Year})` which was suggested here.

**Comment by TRaSH-** [comment]
> This was closed automatically for some reason but does look like a good change to me.

In general, we only make/discuss suggestions on our Discord, and after we agree that it needs to be changed/fixed, we move it to a GHI.
