### ISSUE TITLE
Exclude Mic/Line dubbed releases

### ISSUE THREAD

**Issue by tommyguuuun** [TRaSH-/Guides#1120]
Is there a way to exclude any releases coming with a mic/line dubbed tag? There are some releases 4k, dv, hdr - they got such a high score because of that, but the mic sound quality is bad.

can i avoid it my adding a „mic“ custom format and set it to -10000? If yes, how to do that?

**Comment by TRaSH-** [comment]
you will need to provide release names so we can see how it looks like,
but i guess these are german releases ?
because quality 4k stuff don't have audio like that.
or you're downloading cams

**Comment by TRaSH-** [comment]
Hmm you could block ac3ld and ac3md

**Comment by tommyguuuun** [comment]
Would you mind to help me, how to properly do that?

**Comment by TRaSH-** [comment]
I'm at work now and won't be home before this evening, if I don't forget I will try to manage it this evening

**Comment by tommyguuuun** [comment]
Thanks in advance! It would also be nice to exclude „LD“ which means line dubbed… i think there are several tags for it

**Comment by TRaSH-** [comment]
Could you provide a few release names

**Comment by tommyguuuun** [comment]
just found these two tags - „LD“ and „AC3LD“. There might be more out there, but couldn‘t figure it out yet…

Father.Stu.2022.German.DL.LD.DV.2160p.WEB.h265-PRD

Jeepers.Creepers.Reborn.2022.German.DL.LD.2160p.HDR.WEB.H265-ZeroTwo

Jurassic.World.Ein.neues.Zeitalter.2022.German.DL.LD.DV.2160p.WEB.h265-PRD

Terminator.Dark.Fate.2019.German.AC3LD.DL.2160p.WEB.x264-miUHD

Uncharted.2022.German.AC3LD.5.1.DL.2160p.UHD.BluRay.REMUX.HEVC.HDR.DV.TrueHD.7.1-GLD

**Comment by TRaSH-** [comment]
the problem is i can't do LD only
because of false positive

Is the following correct ?
LD= Line Dubbed
MD=Mic Dubbed

Any reason someone would prefer these ?

**Comment by tommyguuuun** [comment]
Yeah, that‘s correct. Line dubbed (sound extracted in cinema by cable) is way better than mic dubbed (just by microphone), but both are shitty quality. And as we both now - quality is trump, so i guess both should be avoided completely.

**Comment by TRaSH-** [comment]
```json
{
  "name": "Line/Mic Dubbed",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "Line Dubbed",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "\\b(LD|AC3LD)\\b"
      }
    },
    {
      "name": "Mic Dubbed",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "\\b(MD|AC3MD)\\b"
      }
    }
  ]
}
```

Give this a try with a score of -10kl

**Comment by tommyguuuun** [comment]
Thanks so much TRaSH, you‘re awesome!

**Comment by TRaSH-** [comment]
Does everything work as expected ?

**Comment by tommyguuuun** [comment]
Yes, works pretty perfect so far - all line releases where avoided.

**Comment by lyrad87** [comment]
Could we add this somewhere as a Tip or under Misc/Optional with the info that this applies to the German scene only? I've had a similar Custom Format set up but I'll use yours now as well because it's just so much better.

**Comment by TRaSH-** [comment]
> Could we add this somewhere as a Tip or under Misc/Optional with the info that this applies to the German scene only? I've had a similar Custom Format set up but I'll use yours now as well because it's just so much better.

Does it work as expected?
Or do you have suggestions or issues where it doesn't match ?
Would the same rule apply to sonarr?

**Comment by lyrad87** [comment]
These were blocked with the CF above:
`Black.Panther.Wakanda.Forever.2022.German.LD.BDRip.x264-PRD`
`Black.Panther.Wakanda.Forever.2022.German.MD.1080p.CAM.x265-FSX`
`Terminator.Dark.Fate.2019.German.AC3LD.DL.1080p.BluRay.x264-LameHD`

There were not blocked:
`Dirty.Grandpa.2016.German.TS.AC3.MiC.DUBBED.XViD-CiNEDOME`
`Operation.Fortune.2023.German.AC3.Mic.Dubbed.TSRip.x264-HQXD`

So if we want to be thorough and capture all the low-quality audio with the CF, it would need to incorporate the following:
AC3MD
AC3LD
Mic
Mic.Dubbed
MiC
MiC.DUBBED
MD
LiNE
LiNE.DUBBED
LD

Maybe there are some others I missed. @tommyguuuun do you have other suggestions that I've missed?

**Comment by tommyguuuun** [comment]
@lyrad87 nope, i think you did a perfect job! I did a research on some scene sites and that should be everything.

**Comment by TRaSH-** [comment]
well CF are case insensitive so no need to add the different case types
https://regex101.com/r/6vHBAD/1

```json
{
  "name": "Line/Mic Dubbed",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "Line Dubbed",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "\\b(LD|AC3LD|Line[ .-]?Dubbed)\\b"
      }
    },
    {
      "name": "Mic Dubbed",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "\\b(MD|AC3MD|Mic[ .-]?Dubbed)\\b"
      }
    }
  ]
}
```

**Comment by lyrad87** [comment]
Good stuff. I think that’s perfect. Works on all of the releases above. There may be an issue we are not thinking about but we could create a new issue in case it appears. Thanks for the improved CF!

**Comment by TRaSH-** [comment]
Would the same rule apply to sonarr?

**Comment by lyrad87** [comment]
I don't think so. I have yet to see a Line or Mic release.

**Comment by TRaSH-** [comment]
so i only need to add it to Radarr

**Comment by tommyguuuun** [comment]
There is another unwanted sound profile, which comes as „AC3 dubbed“

I.e. this release: Plane.2023.German.DL.AC3.Dubbed.2160p.HDR.DV.WEB.h265-PsO

ac3 dubbed always have poor stereo quality, maybe you could include it to the line dubbed profile or create a new one?
