### ISSUE TITLE
[Bug] Joining Discord

### ISSUE THREAD

**Issue by tc60045** [TRaSH-/Guides#113]
Try creating a new account for Discord
Follow "join discord" from your trash-guides.info site
HawkBot asks you to give a :thumbsup: reaction to agree to the rules
Impossible to do so -- click on Reactions for that post and you cannot add anything to it, including a: thumbsup:
=> cannot join discord channel
![by default 2021-01-24 at 12 32 14 PM](https://user-images.githubusercontent.com/2856318/105639889-498fa280-5e40-11eb-84d8-f30df590c76c.jpg)
![by default 2021-01-24 at 12 31 54 PM](https://user-images.githubusercontent.com/2856318/105639890-4a283900-5e40-11eb-9b58-4d50a64c6af2.jpg)

Bot logic for discord is very sensitive - tons of configuration challenges by channel owners on stack exchange.   Entirely possible, though, that the issue is just a dumb user (me), hence I suggest you try the above to see whether you have better luck.  Thx.

**Comment by austinwbest** [comment]
I just clicked the existing thumb emoji and it worked. 🤔

**Comment by TRaSH-** [comment]
![image](https://user-images.githubusercontent.com/6155095/105644461-f9dbc600-5e95-11eb-83c0-7b3f0b59358a.png)
