### ISSUE TITLE
HBO/HMAX CF/RP Consistency

### ISSUE THREAD

**Issue by yammes08** [TRaSH-/Guides#1141]
**Which Guide**
Radarr/Sonarr V3/Sonarr V4

**Describe the Error in the Guide**
HBO/HMAX isn't treated consistently across the guide:

Sonarr V3
HMAX: `/\\b(hmax|hbom|hbo max)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i` - score 90
HBO: `/\\b(hbo)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i` - score 75

Sonarr V4
HMAX: `\\b(hmax|hbom|hbo max)\\b` - score 90
HBO: `\\b(hbo)(?![-_. ]max)\\b` - score 75 (PR pending to fix issue with matching -HBO rlsgrp)

Radarr V4
HMAX: `\\b(hmax|hbom|HBO Max)\\b` - no score
HBO: N/A

**Expected behavior**
To apply a consistent approach

**Screenshots**
N/A

**Additional context**
N/A

**Comment by TRaSH-** [comment]
Radarr doesn't have scoring for streaming services except 2.

there seems to be a difference between HBO and HBO MAX
that's why they have different scores

**Comment by yammes08** [comment]
How about this:

Sonarr V3
HMAX: /\\b(hmax|hbom|hbo[-_. ]max)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i
HBO: /\\b(hbo)(?![-_. ]max)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)/i

Sonarr V4
HMAX: \\b(hmax|hbom|hbo[-_. ]max)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)
HBO: \\b(hbo)(?![-_. ]max)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)

Radarr V4
HMAX: \\b(hmax|hbom|hbo[-_. ]max)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b) - no score
HBO: \\b(hbo)(?![-_. ]max)\\b(?=[ ._-]web[ ._-]?(dl|rip)\\b)

Scores remain unchanged, new Radarr CF (if needed?) gets no score.
