### ISSUE TITLE
[Bug]  Discord invite expired?

### ISSUE THREAD

**Issue by jeff47** [TRaSH-/Guides#1165]
Not really a bug, but when clicking on your links for Discord, it says they have expired.

**Comment by TRaSH-** [comment]
hmm, thnx let me check. i didn't have a expiration date on it. must be a discord glitch
will fix it asap

**Comment by jeff47** [comment]
Sorry, might need to be more specific:  it says the link is invalid, which *might* be because it expired.  Potentially could be an issue on my end, but Discord is working for me otherwise.

<img width="492" alt="Screen Shot 2023-02-17 at 7 35 47 AM" src="https://user-images.githubusercontent.com/7215369/219655227-c9eb84ad-8664-40fc-99f8-2ce144ca7ac4.png">

**Comment by TRaSH-** [comment]
i just tried with a incognito window and that worked
could you try the following
https://discord.gg/4K2kdvwzFh

**Comment by TRaSH-** [comment]
which link did you use, or where did you get it from ?

**Comment by jeff47** [comment]
Must have been a local glitch... switched browsers and it worked.  Sorry!
