### ISSUE TITLE
HLG not included in SDR as HDR Format

### ISSUE THREAD

**Issue by dcglabs** [TRaSH-/Guides#1168]
https://github.com/TRaSH-/Guides/blob/master/docs/json/sonarr/cf/sdr.json
https://github.com/TRaSH-/Guides/blob/master/docs/json/radarr/cf/sdr.json

```
      "name": "HDR Formats",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": false,
      "fields": {
        "value": "\\bHDR(\\b|\\d)|\\b(dv|dovi|dolby[ .]?vision)\\b|\\b(FraMeSToR|HQMUX|SiCFoI)\\b|\\b(PQ)\\b"
```

Doesn't include HLG. Thus when run on item with HLG it gets scored as SDR. Adding HLG allows for proper HLG scoring. 
`\\bHDR(\\b|\\d)|\\b(dv|dovi|dolby[ .]?vision)\\b|\\b(FraMeSToR|HQMUX|SiCFoI)\\b|\\b(PQ)\\b|\\b(HLG)\\b`

**Comment by TRaSH-** [comment]
Thnx for reporting will be fixed as soon as PR #1169 has been merged
