### ISSUE TITLE
[Bug] Radarr not adding Freeleech indexer flag to custom format score on search

### ISSUE THREAD

**Issue by RyanAStrouse** [TRaSH-/Guides#1192]
**Which Guide**
No guide, general use of custom formats and freeleech indexer flag and scores not calculating correctly.

**Describe the Error in the Guide**
Custom indexer score is not generating correctly when searching indexer items that have a freeleech flag. However, if downloaded manually the history shows the "FreeLeech" custom format tag and correct score.

**Expected behavior**
An item that has a freeleech flag should add the custom value to the score on search.

**Screenshots**
![image](https://user-images.githubusercontent.com/4588529/221931122-29020ff0-2005-46a8-9f80-56b46c9eecaf.png)

![image](https://user-images.githubusercontent.com/4588529/221930997-4a5ea9bb-79ed-4978-8012-da00b7c09301.png)

![image](https://user-images.githubusercontent.com/4588529/221931362-2539b80b-63ec-44a0-99e6-46b95fa4d13b.png)

![image](https://user-images.githubusercontent.com/4588529/221931581-ac7685bb-8e87-48f0-9a51-a5847ae36ffd.png)

**Additional context**
```
Version
4.4.3.6983
Package Version
nightly-9f4152d by hotio
```

Trace logs
https://pastebin.com/ytmFhyMv

**Comment by bakerboy448** [comment]
=> Radarr GHI
not a guide issue
