### ISSUE TITLE
Issue with Completed destination example for NZBGet 

### ISSUE THREAD

**Issue by DomNixon** [TRaSH-/Guides#1232]
The following guide shows the completed destination should be ${MainDir}/complete while the correct destination is ${MainDir}
Having this incorrect results in a Remote Path error 

https://trash-guides.info/Hardlinks/Examples/

**Comment by bakerboy448** [comment]
Should be fine as is.

what's the EXACT error?
Docker? what's your mounts?

**Comment by DomNixon** [comment]
Yeah that was my understanding as well which is why I spent a lot of time hunting this down. The issue is same as noted in the guide. The paths were identical in unraid for the container and host path as noted here - https://trash-guides.info/Hardlinks/How-to-setup-for/Unraid/ I had also followed the examples listed which left the /complete for destination in NZBGet which conflicts with this info: 

"Info

The reason why we use /data/usenet/ for the usenet client is because it only needs access to the usenet files. In the usenet software settings, you’ll need to reconfigure paths and you can sort into sub-folders like /data/usenet/{tv|movies|music}."

Movies would end up in /data/usenet/complete/movies instead of /data/usenet/movies

This results in the Paths looking like this (No /Complete for DestDir) 
![image](https://user-images.githubusercontent.com/1761152/227345287-e6958544-23ef-4a62-8451-51f433181a01.png)

**Comment by bakerboy448** [comment]
Again please provide the reuqested information

**Comment by DomNixon** [comment]
Apologies, just trying to help pass on the info since this stumped me for a minute. To accommodate I broke my setup back to the error state and took the required screenshot to show the issue. Apologies if this is long and wordy, I was not clear in the last response and would love to understand were I am misunderstanding if I am. 

First this should be noted we are specific looking at Radarr and NZBGet

Following the Unraid guide listed [here](https://trash-guides.info/Hardlinks/How-to-setup-for/Unraid/) This guide does not ask for us to create /data/usenet/movies/completed so I did not create that, ~~that may resolve the error as well~~. Tried with the folder **complete** created and same error.  Here are my docker mounts which align with the article. 

![image](https://user-images.githubusercontent.com/1761152/227660204-ae1b1207-68ce-426b-902c-40bf3934103f.png)

I spent multiple hours thinking this was somehow incorrect somehow and was causing this error: 

![image](https://user-images.githubusercontent.com/1761152/227660424-2263ff9a-875a-4408-8967-df4b64070de6.png)

What I found was the [example](https://trash-guides.info/Hardlinks/Examples/) I was following for the configuration inside NZBGet was causing the error. 

This causes the error:
![image](https://user-images.githubusercontent.com/1761152/227661064-cf2e6e75-5c98-434b-9027-f97877adba2b.png)

This does not:
![image](https://user-images.githubusercontent.com/1761152/227661131-469451e4-705b-46a9-8ba2-a9231685008b.png)

**Comment by yammes08** [comment]
The reason you're getting the error is because that folder doesn't exist, however that folder (`/completed`) will be created the first time something is downloaded. If you switch back to your 'error state', then grab something, once it's complete that error will probably go away.

**Comment by DomNixon** [comment]
Interesting thank you, will give that a try, I have the folder created already.
