### ISSUE TITLE
[Bug] Sonarr v3 ReleaseRestrictionsSpecification parsing error

### ISSUE THREAD

**Issue by tomislav** [TRaSH-/Guides#1237]
I'm getting an error in Sonarr v3.0.10.1567.

`ReleaseRestrictionsSpecification: parsing "^(?!.*(web[ ]dl|-deflate|-inflate))(?=.*([_. ]WEB[_. ])(?!DL)\b)|\b(-CAKES|-GGEZ|-GGWP|-GLHF|-GOSSIP|-NAISU|-KOGI|-PECULATE|-SLOT)).*" - Too many )'s.`

It seems to be caused by commit https://github.com/TRaSH-/Guides/commit/ae9fbf4f1b33dfef4112984acd97460691068d91

**Comment by TRaSH-** [comment]
Fixed with PR #1238
