### ISSUE TITLE
Error in replace_for.py

### ISSUE THREAD

**Issue by bsmith76s** [TRaSH-/Guides#1249]
**Which Guide**
Sabnzb

**Describe the Error in the Guide**
keep getting an error when download finishes and starts processing

**Expected behavior**
should unpack and then radar pick it up 

**Screenshots**
Completed
16 hours ago
Status
Completed
Size
4.7 GB
Category
movies
Path
/nzb/complete/movies/.2014.LIMITED.1080p.BluRay.x264-FBV
Source
.2014.LIMITED.1080p.BluRay.x264-FBV.nzb
Download
Downloaded in 21 mins 41 seconds at an average of 3.7 MB/s
Age: 3268d
Servers
news.frugalusenet.com=0 B, EuNews=0 B, BonusFrugal=0 B, BlockNews=4.7 GB
Repair
 [.2014.LIMITED.1080p.BluRay.x264-FBV] Verified in 17 seconds, all files correct
Unpack
[.2014.LIMITED.1080p.BluRay.x264-FBV] Direct Unpack - Unpacked 5 files/folders in 8 seconds
Script
Exit(1) SyntaxError: expected 'except' or 'finally' block [(More)](http://xx.xx.xx.xx.250:10097/scriptlog?name=SABnzbd_nzo_lzycds9b)

**Additional context**
File "/nzb/scripts/replace_for.py", line 26
except ValueError:
SyntaxError: expected 'except' or 'finally' block

I have tried adjusting the indentation but still keep getting error.

**Comment by TRaSH-** [comment]
I personally suggest to join the discord support channel
but which version of sabnzbd are you running?
