### ISSUE TITLE
[Bug] Recyclarr: Incorrect usage of reset_unmatched_scores

### ISSUE THREAD

**Issue by uhthomas** [TRaSH-/Guides#1256]
**Which Guide**

https://trash-guides.info/Recyclarr/recyclarr-configs

**Describe the Error in the Guide**

The configs use `reset_unmatched_scores` for `quality_profiles` where they shouldn't.

**Expected behavior**

According to the [documentation](https://recyclarr.dev/wiki/yaml/config-reference/) and [schema](https://recyclarr.dev/wiki/schema-validation/), there are two kinds of quality profile.

Example schema:

```cue
radarr: [string]: {
    quality_profiles: [...{
        name: string
        reset_unmatched_scores: bool
    }]
    custom_formats: [...{
        quality_profiles: [...{
            name: string
            score: int
        }]
    }]
}
```

The field `reset_unmatched_scores` is incorrectly being used for the custom format quality profile, which doesn't exist.

It looks like it used to, though.

https://github.com/recyclarr/recyclarr/blob/503cb7500a81076ff0c1e9279152ebf23418fd62/src/Recyclarr.TrashLib/Pipelines/QualityProfile/PipelinePhases/QualityProfileConfigPhase.cs#L97-L100

**Screenshots**

N/A

**Additional context**

N/A

**Comment by yammes08** [comment]
This was deprecated with the latest release of recyclarr, which only came out 7 hours ago 😄 I should be able to take a look at this today.

**Comment by yammes08** [comment]
These will be updated with PR #1257
