### ISSUE TITLE
[Bug]fix radarr flowchart guide for 4k

### ISSUE THREAD

**Issue by bakerboy448** [TRaSH-/Guides#1292]
**Which Guide**
Please add which Guide you found a Bug/Error with.

radarr cfs 

**Describe the Error in the Guide**

flow chart gudie for remux + web points to 1080p and 2160p without considering if they want 4k

redo flowchart and guide for remux + web to have a branch of 4k/1080p so the proper quality profile can be more easily referenced

![IMG_3111](https://user-images.githubusercontent.com/55419169/236455517-c9f54581-8731-426b-afe9-6e7361b1f9ff.png)

**Expected behavior**

**Screenshots**

That flowchart guide is slightly off since it points the web remux to both 1080 and 4k but ignored the 4k of not question

**Additional context**

**Comment by TRaSH-** [comment]
One of the first flowcharts concepts had that option
What resulted in some weird loops in the charts or even adding HDR formats to 1080p or it got as huge and complicated as the tracker chat
And when you need to scroll from left to right from top to bottom and back, it's getting more complicated then needed
And I would need to add another full described quality profile.
Now we can say he you want 1080p and 2160p remuxes, just follow and add both to 1 qualify profile

**Comment by bakerboy448** [comment]
I think the first question should be 4k or not and then go from there?  Have we explored that as a tree?

**Comment by TRaSH-** [comment]
Yes and then I get 2x the question if you want remuxes or encodes
One for the 1080p and one for the 2160p
And the same counts for the audio formats
