### ISSUE TITLE
[Bug] - Vinegar Syndrome - false positive on movie titles `vs.`

### ISSUE THREAD

**Issue by bakerboy448** [TRaSH-/Guides#1314]
**Which Guide**
Radarr-collection-of-custom-formats

**Describe the Error in the Guide**
VS regex is too vauge
`\b(V-?S)\b`
`Kramer vs. Kramer (1979) {imdb-tt0079417} [Bluray-1080p][DTS 5.1][x264]-CtrlHD.mkv` should not match
`Godzilla vs. Kong (2021) {imdb-tt5034838} [Bluray-1080p][EAC3 7.1][x264]-DON.mkv` should not match
`Rocky.IV.Rocky.vs.Drago.1985.Ultimate.Directors.Cut.1080p.AMZN.WEB-DL.DDP5.1.H.264-TEPES.mkv` should not match

**Expected behavior**
`vs.` in a title is not vinegar syndrome

**Screenshots**

**Additional context**

**Comment by nuxencs** [comment]
I did yeah, did not take that into consideration
