### ISSUE TITLE
[REQUEST] Guide to integrate homepage project

### ISSUE THREAD

**Issue by uebmaster** [TRaSH-/Guides#1336]
**For which application would like to see this Guide ?**
Radarr / Sonarr / Bazarr / etc

All the stock

**Describe what you would like to see in the Tutorial/Guide**
A clear and concise description of what you want to see in the Guide .

The way to integrate all the arr apps (including jellyseerr) with the homepage project: https://github.com/benphelps/homepage

**Comment by TRaSH-** [comment]
I took a look at it, but at the moment i don't have any plans to write a guide for this, because the next guide request will be for organizr, heimdall etc.
Also i'm not using it either.

**Comment by bakerboy448** [comment]
> Ok, but in place of hemdall you can implement Homeland

completely ignores the mountain of requests that would fall out
> Second because the next guide request will be for organizr, heimdall etc.

**Comment by uebmaster** [comment]
ok, anyway thanks, great job (Y)
