### ISSUE TITLE
[Bug] Radarr 4.x getting Unknown Custom Format condition 'ReleaseGroupSpecification' using "Import" 

### ISSUE THREAD

**Issue by joridiculous** [TRaSH-/Guides#1347]
**Which Guide**
[Please add which Guide you found a Bug/Error with.]
(https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats/#remux-tier-01)

**Describe the Error in the Guide**
When paste the JSON in the empty Custom Format JSON box (1) that you got from the [Custom Format Collection](https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats/) followed by the Import button, Radarr throws the error "Unknown Custom Format condition 'ReleaseGroupSpecification'"

**Expected behavior**
No error basically. I have imported custom format fromt he guide before. 

**Screenshots**
not sure if needed but i added two

**Additional context**
![Screenshot (5847)](https://github.com/TRaSH-/Guides/assets/25628732/dbf8d4cc-0229-4157-a7e6-7e5676db2710)
![Screenshot (5849)](https://github.com/TRaSH-/Guides/assets/25628732/490c6b2e-965c-41ef-8587-5d334f993ff5)

**Comment by yammes08** [comment]
What version of Radarr are you using?

**Comment by bakerboy448** [comment]
Not a bug. Upgrade radarr. Your version is very out of date.

4.X is not a valid radarr version.
4.5.2 is current master
