### ISSUE TITLE
P2P Groups + Repack/Proper

### ISSUE THREAD

**Issue by cphmichael** [TRaSH-/Guides#142]
https://trash-guides.info/Sonarr/V3/Sonarr-Release-Profile-RegEx/

If you compare the "P2P Groups + Repack/Proper" guide to the green 'example' below, the last line says "/\b(repack|proper)\b/i" with a score of [10].

If you look in the green example below, the same line says "/(repack|proper)/i" (without the \b before and after the expression.

In the "Low Quality Groups" guide the score of [-100] all ends with "\b", but in the green example below the "/(-VIDEOHOLE)/i" don't end with "\b".

Should my final result look like the green 'example' or the guide above?

**Comment by TRaSH-** [comment]
the screenshots are examples, you should always follow the guide lines it self where you can copy paste what you need to add.
![image](https://user-images.githubusercontent.com/6155095/107852138-38b6c900-6e0f-11eb-8904-f34d73206b9e.png)

i considered a point where to remove all the screenshots, but then it seems people are having issues where to add it.
