### ISSUE TITLE
Sonarr V3: Prioritize HDR?

### ISSUE THREAD

**Issue by cphmichael** [TRaSH-/Guides#143]
https://trash-guides.info/Sonarr/V3/Sonarr-Release-Profile-RegEx/

Should the guide give a HDR show a higher score so HDR i prioritized over non HDR?

As you can see on the attached screendump the Servant S02E05 has a score of 250 both with and without HDR. 

![image](https://user-images.githubusercontent.com/45288008/107781574-510fe080-6d48-11eb-8492-5bba20dd8d9b.png)

**Comment by TRaSH-** [comment]
If you prefer HDR then yes you can create a additional entry that prefers HDR with a extra score of 1.

This isn't a BUG/Error so closing this down,
Both your questions could probably have been asked and answered in the Discord channel faster.

![image](https://user-images.githubusercontent.com/6155095/107852281-2be6a500-6e10-11eb-9c28-62a56975f6ea.png)
