### ISSUE TITLE
[Feature] Consider adding delay profile for Sonarr v3

### ISSUE THREAD

**Issue by pikeas** [TRaSH-/Guides#167]
I recently added your profiles to Sonarr, great work and fantastic resource! With the new setup, I'm seeing more downloads than I'd like, due to upgrades.

For currently airing shows, I'd love to see just two downloads:
* First release ASAP (or slight delay to skip 720 when 1080 lands a few minutes later).
* Second release 12-24 hours later: if I didn't watch the show immediately, let's wait for the best version

Do you think there's a way to accomplish this using delay profiles or other tricks?

**Comment by bakerboy448** [comment]
FYI https://github.com/Sonarr/Sonarr/issues/4301

You can use delay profiles, but they only wait for the max QUALITY to be reached.
Preferred words are not in that scope.


This is what I use FWIW
![image](https://user-images.githubusercontent.com/55419169/110155331-16c7bb00-7dab-11eb-83ea-8067b6a82877.png)

**Comment by TRaSH-** [comment]
> I recently added your profiles to Sonarr, great work and fantastic resource! With the new setup, I'm seeing more downloads than I'd like, due to upgrades.
> 
> For currently airing shows, I'd love to see just two downloads:
> 
> * First release ASAP (or slight delay to skip 720 when 1080 lands a few minutes later).
> * Second release 12-24 hours later: if I didn't watch the show immediately, let's wait for the best version
> 
> Do you think there's a way to accomplish this using delay profiles or other tricks?

it's more personal preference and no BUG,
support questions should actually be done on discord.

![image](https://user-images.githubusercontent.com/6155095/110176205-3c80ae80-7e03-11eb-9042-991bef0e53bd.png)
