### ISSUE TITLE
[Suggestion] Suggestions on custom format profile names in Radarr

### ISSUE THREAD

**Issue by pikeas** [TRaSH-/Guides#168]
Here are some name suggestions for more consistency in naming conventions:

* 4k Remaster -> Remaster (4K)
* Basic DTS -> DTS
* Basic Dolby Digital -> DD
* Dolby Digital Plus -> DD+
* DD+ ATMOS (lossy) -> DD+ ATMOS
* DTS-HD/DTS:X -> DTS (HD or X)
* Dolby Vision (Single Layer) -> DoVi (Single Layer)
* EVO except WEB-DL -> EVO (no WEB-DL)
* HDR (indeterminate) -> HDR (guessed)
* HQ-P2P -> Release (high quality)
* Low Quality Releases -> Release (low quality)
* Streaming Services -> Streaming
* Surround Sounds -> Surround Sound
* TrueHD (not ATMOS) -> TrueHD
* TrueHD ATMOS -> TrueHD (ATMOS)
* 720/1080p no x265 -> x265 (720/1080p): the profile regex matches only 265, it's dis-preferred by using a negative score.

**Comment by TRaSH-** [comment]
> * 4k Remaster -> Remaster (4K)

To my knowledge 4k Remastered is the official naming

> * Basic DTS -> DTS
> * Basic Dolby Digital -> DD
> * Dolby Digital Plus -> DD+

Might consider it, but the ones we use now does a better description. but i could add the expanded description to the guide. 

> * DD+ ATMOS (lossy) -> DD+ ATMOS


> * DTS-HD/DTS:X -> DTS (HD or X)

personally i dislike this custom format and actually would like to remove it from the table, but still a few people like it,
changing to what you suggest is less consistent if you compare it with what you suggest with `DTS`, `DD` and `DD+`

> * Dolby Vision (Single Layer) -> DoVi (Single Layer)

Not a bad idea or perhaps even `Dovi (SL)`

> * EVO except WEB-DL -> EVO (no WEB-DL)

Might Consider it.

> * HDR (indeterminate) -> HDR (guessed)

indeterminate = not exactly known, established, or defined
After import and media info from Radarr it should change to `HDR`

> * HQ-P2P -> Release (high quality)

I don't like long names ;)

> * Low Quality Releases -> Release (low quality)

I actually wanted to use `LQ`

> * Streaming Services -> Streaming

Might Consider it.


> * Surround Sounds -> Surround Sound

Same as with `DTS-HD/DTS:X`, But will consider it.

> * TrueHD (not ATMOS) -> TrueHD

Might Consider it.

> * TrueHD ATMOS -> TrueHD (ATMOS)

Don't like the use of round brackets for a import part of the audio format

> * 720/1080p no x265 -> x265 (720/1080p): the profile regex matches only 265, it's dis-preferred by using a negative score.

Might Consider it.

**Comment by TRaSH-** [comment]
@pikeas 
the changes i considered to do, should they also be the same in the table overview or only the CF name that shows in Radarr ?

**Comment by pikeas** [comment]
> @pikeas
> the changes i considered to do, should they also be the same in the table overview or only the CF name that shows in Radarr ?

That's a good question, I'm not sure. I would lean towards full name in the table, with a note that the short names are sometimes different for readability in the app.

**Comment by TRaSH-** [comment]
Perhaps not everyone will understand that:
DoVi = Dolby Vision
EVO (no WEB-DL) means except WEB-DL

> That's a good question, I'm not sure. I would lean towards full official name in the table, with a note that the short names are sometimes different for readability in the app.

So the main goal would be shorter CF names what Radarr shows.
let me set it up on my test server

**Comment by TRaSH-** [comment]
@pikeas did a PR #171 with a few changes following your suggestions.

**Comment by TRaSH-** [comment]
Merged with #171
