### ISSUE TITLE
Last update: 3 days ago > What is updated?

### ISSUE THREAD

**Issue by cphmichael** [TRaSH-/Guides#181]
Thank you for your nice guides.
I have setup my Radarr and Sonarr according to your guide.
When I enter your guide a month later I can see it says "Last update: 3 days ago".
Do you have a 'history' where I can see what is updated / changed, so I can enter the latest updates into my Radarr and Sonarr?
Regards
Michael

**Comment by tronyx** [comment]
This isn't a bug. You can look at the commit history like you can with any repo to see what was changed. You can also join the Discord Server, linked on the main site, which contains a change log channel to see what was done.

**Comment by TRaSH-** [comment]
![image](https://user-images.githubusercontent.com/6155095/112359003-2020b500-8cd1-11eb-8dcd-64a297a23858.png)

and I already mentioned this before  #143
This isn't a BUG/Error so closing this down,
Your questions could probably have been asked and answered in the Discord channel faster.
