### ISSUE TITLE
[Bug] Sonarr anime bluray regex does not capture mini encodes.

### ISSUE THREAD

**Issue by ArabCoders** [TRaSH-/Guides#275]
** Which Guide **
https://trash-guides.info/Sonarr/Sonarr-Release-Profile-RegEx-Anime/

**Describe the Error in the Guide**
The bluray regex

```
/\b(?:(BluRay|Blu-Ray|BDMux|BD(?!$))|(BDRip)|(BRRip))(?:\b|$|[ .])/ix
```
does not capture popular release scheme with groups like DB and Cleo  

**Expected behavior**
the expected behavior is to match BD1080p in the string

**Screenshots**
![regex-test-fail](https://user-images.githubusercontent.com/1621552/122591542-c4fe2480-d06b-11eb-9bb0-1251f8e65dca.png)

**Additional context**

by changing the regex pattern to this im able to capture them
```
/\b(?:(BluRay|Blu-Ray|BDMux|BD(?!$))|(BDRip)|(BRRip))(?:\b|$|[ .])|BD[0-9]{4}(p|i)/ix
```

**Comment by TRaSH-** [comment]
@Visorask could you take a look being it's anime related.

**Comment by Visorask** [comment]
Cursory glance at various sites BD1080P is not a standard naming scheme for most groups that aren't low quality / re-encoded / or mini-sized. Also Cleo / DB may be popular but there is a reason that they are included in the -10000/-15000 release scheme. This guide for anime is mostly dual audio / high quality. I can include it as it doesn't seem to make too much of a difference especially if people have the lower releases set as the guide is written. But the problem with making a change like this is if / when people update, especially with something like recyclarr, it can set off a chain of "upgrades" for people, whether good or bad.

So I'll do this, when I get back from my field work I'll take a good look into the pros / cons and how it will affect people to ensure no major issues, outside of just these few groups.

**Comment by ArabCoders** [comment]
i honestly think mini encodes are perfectly fine for most anime unless its like high production. i.e (demon slayer, violet Evergarden, those should be watched in high bitrate. feels bit waste not to). i default to mini encodes unless the show demands it. most anime compress well unlike tv shows. some might think judas/cleo and db are bad. i use 4k tv and i barely can tell the difference unless it has pitch black long segment in which case some sand grain might be visible. 

in any case i think this filter should be general catch all for BD. and like you said have another filter for un-wanted groups.

**Comment by TRaSH-** [comment]
I don't maintain the anime section,
But the main guide is based on quality releases (where quality could be several meaning picture quality or audio wise)
And mini encodes wouldn't fit in it in my opinion.
There is a reason why we have certain groups in the LQ section so it will be ignored like the releases from yify.
Even that some people prefer them.
You may consider that certain shows are okay as mini encodes, but others might disagree because they like those shows.

So this is certainly not a bug but a personal preference.
Something you can add to your Sonarr for own use.

The guides are more or less a guidance and users can edit it anyway they prefer to their liking in their own setup.

**Comment by ArabCoders** [comment]
Oh, i agree i think quality is preference that should be left up to user to choose what they want, i just think general catch all Bluray regex is more preferred. not really a personal opinion. if you disagree you are free to close this as non-issue.

**Comment by Visorask** [comment]
@ArabCoders No I do agree we should catch all versions of a Blu-ray release, I just want to verify it is not going to affect any other groups besides lower ones as I did not have a chance to make sure it would not affect anything else. I'm always open to add things especially when someone puts in the effort themselves, just wanna ensure no other issues will arise. 

But from looking at it it should not affect anything and I will add this into my next update as I have some groups and other things I need to correct as well.

Apologies if I came off like a dick, wasn't my intention, just trying to explain my thought process as well from the other side.

**Comment by ArabCoders** [comment]
Oh.. no worries mate, i didn't think you offended me or anything. i just wanted to explain how i see things =)

Thank you. And have nice day.

**Comment by skarekrow** [comment]
> Cursory glance at various sites BD1080P is not a standard naming scheme for most groups that aren't low quality / re-encoded / or mini-sized. Also Cleo / DB may be popular but there is a reason that they are included in the -10000/-15000 release scheme. This guide for anime is mostly dual audio / high quality. I can include it as it doesn't seem to make too much of a difference especially if people have the lower releases set as the guide is written. But the problem with making a change like this is if / when people update, especially with something like recyclarr, it can set off a chain of "upgrades" for people, whether good or bad.
> 
> So I'll do this, when I get back from my field work I'll take a good look into the pros / cons and how it will affect people to ensure no major issues, outside of just these few groups.

Totally not related, but what is recyclarr? First I've heard of it.

In my opinion we should *not* be adding this, these groups are LQ by nature, and look/sound worse than the equivalent SubsPlease releases, despite being sourced from a Bluray. I think they should be in the LQ group and somebody can bump them, I'd personally find it shocking to see them preferred as if they were a higher quality release than the web streaming platforms. No offense to @ArabCoders at all, but imo this should not belong in the general Bluray category.

**Comment by ArabCoders** [comment]
> > Cursory glance at various sites BD1080P is not a standard naming scheme for most groups that aren't low quality / re-encoded / or mini-sized. Also Cleo / DB may be popular but there is a reason that they are included in the -10000/-15000 release scheme. This guide for anime is mostly dual audio / high quality. I can include it as it doesn't seem to make too much of a difference especially if people have the lower releases set as the guide is written. But the problem with making a change like this is if / when people update, especially with something like recyclarr, it can set off a chain of "upgrades" for people, whether good or bad.
> > So I'll do this, when I get back from my field work I'll take a good look into the pros / cons and how it will affect people to ensure no major issues, outside of just these few groups.
> 
> Totally not related, but what is recyclarr? First I've heard of it.
> 
> In my opinion we should _not_ be adding this, these groups are LQ by nature, and look/sound worse than the equivalent SubsPlease releases, despite being sourced from a Bluray. I think they should be in the LQ group and somebody can bump them, I'd personally find it shocking to see them preferred as if they were a higher quality release than the web streaming platforms. No offense to @ArabCoders at all, but imo this should not belong in the general Bluray category.

non taken. I just feel this filter shouldn't consider high/low criteria, it should just match BD releases regardless of what you or i consider good quality.

**Comment by skarekrow** [comment]
> > > Cursory glance at various sites BD1080P is not a standard naming scheme for most groups that aren't low quality / re-encoded / or mini-sized. Also Cleo / DB may be popular but there is a reason that they are included in the -10000/-15000 release scheme. This guide for anime is mostly dual audio / high quality. I can include it as it doesn't seem to make too much of a difference especially if people have the lower releases set as the guide is written. But the problem with making a change like this is if / when people update, especially with something like recyclarr, it can set off a chain of "upgrades" for people, whether good or bad.
> > > So I'll do this, when I get back from my field work I'll take a good look into the pros / cons and how it will affect people to ensure no major issues, outside of just these few groups.
> > 
> > 
> > Totally not related, but what is recyclarr? First I've heard of it.
> > In my opinion we should _not_ be adding this, these groups are LQ by nature, and look/sound worse than the equivalent SubsPlease releases, despite being sourced from a Bluray. I think they should be in the LQ group and somebody can bump them, I'd personally find it shocking to see them preferred as if they were a higher quality release than the web streaming platforms. No offense to @ArabCoders at all, but imo this should not belong in the general Bluray category.
> 
> non taken. I just feel this filter shouldn't consider high/low criteria, it should just match BD releases regardless of what you or i consider good quality.

I suppose this is just the "general" category and not the *tiered varieties. Objection removed :D

**Comment by TRaSH-** [comment]
Closed because of no updates after 3 months,
re-open when needed.
