### ISSUE TITLE
Improve identification of Audio Channels

### ISSUE THREAD

**Issue by michpas** [TRaSH-/Guides#334]
** Which Guide **
Radarr

**Describe the Error in the Guide**
Currently it only finds 5.1 and not "5 1" (with a space); This is also a very common writing in file name

**Expected behavior**
for the regex filter to identify both 5.1 and 5 1  as 5.1 surround sound

**Additional context**
The solution is to change the reggex to: [^0-9]5[.|\s][0-1]

**Comment by TRaSH-** [comment]
I'm going to test this when I get home from work.
Seems the regex testers don't like testing on my mobile.

**Comment by TRaSH-** [comment]
did a test and got the following results
OLD Custom Format
![image](https://user-images.githubusercontent.com/6155095/131373925-7d50f237-c3e7-4216-9c87-9b3b88428a6a.png)

So you're right it doesn't pick up `5 1` even that it's not a common thing to show up in the release name, it could happen, being some indexer replace the dots for spaces in the results

I asked someone that helps me with regex questions, and he actually suggest to go for the following
![image](https://user-images.githubusercontent.com/6155095/131374271-d31c3fa6-d95f-462d-995d-3656696af373.png)

This will be changed in the upcoming update of the custom formats, and it will also include all the other audio channels custom format.

**Comment by michpas** [comment]
Great. thanks !
