### ISSUE TITLE
new label DTS -X

### ISSUE THREAD

**Issue by michpas** [TRaSH-/Guides#335]
** Which Guide **
Radarr

**Describe the Error in the Guide**
Found a new missing label,. DTS X; which is used in file names
https://www.whathifi.com/advice/dtsx-what-it-how-can-you-get-it

**Expected behavior**
A label added that detects DTS-X

**Additional context**
Below the filter. Note,this DTS-X als need to be excluded from the existing DTS, DTS-ES, DTS-HD MA, DTS-HD HR

{
  "name": "DTS X",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "DTS X",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "dts[-. ]?x(?!\\d)"
      }
    },
    {
      "name": "Not Basic DTS",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "DTS[ .]?[1-9]"
      }
    },
    {
      "name": "Not Basic Dolby Digital",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "\\bDD(\\b|\\d)|(?<!e)ac3"
      }
    },
    {
      "name": "Not Dolby Digital Plus",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "[^-]dd[p+]|eac3"
      }
    },
    {
      "name": "Not TrueHD/ATMOS",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "TrueHD|\\bATMOS(\\b|\\d)"
      }
    },
    {
      "name": "Not FLAC",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "\\bFLAC(\\b|\\d)"
      }
    },
    {
      "name": "Not AAC",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "\\bAAC(\\b|\\d)"
      }
    },
    {
      "name": "Not PCM",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "\\b(l?)PCM(\\b|\\d)"
      }
    }
  ]
}

**Comment by TRaSH-** [comment]
Do you mean this one ?
https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats/#dts-x

**Comment by michpas** [comment]
Uh, yes. Not sure why i overlooked.
