### ISSUE TITLE
[REQUEST] Update Guides for WEB-DL with DoVi and HDR10 Fallback

### ISSUE THREAD

**Issue by nismanoku** [TRaSH-/Guides#402]
**For which application would like to see this Guide ?**
Radarr / Sonarr 

**Describe what you would like to see in the Tutorial/Guide**
Updated guides for the WEB-DL releases that have DoVi with HDR Fallback. When DoVi is unsupported these will play fine without the green picture DoVi would else cause. Would like to see the option that WEB-DL with DoVi (DV) and HDR in the title would be preferred over regular WEB-DL with HDR and when only DoVi is in the title the release will be ignored, because of the green picture it causes on devices that don't support DoVi.

Radarr is pretty straight-forward; Just created a new Custom Format that needs DoVi (DV) and HDR in the title and updated the profiles score so they are preferred over regular HDR. But maybe there is a better way i don't know off.

But to accomplisch this in Sonarr with profiles is another levell of experience i don't have, so therefore the request.

Thanxs in advance

**Comment by TRaSH-** [comment]
i never have seem them on series, got a few examples ?
or perhaps join discord

**Comment by nismanoku** [comment]
I have added two examples. The second one is going to be difficult as it is not stated in the title and has DV, HDR10 and HDR.

Loki S01 2160p DSNP WEB-DL DDP 5.1 Atmos DoVi HDR HEVC-SiC

`Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5@High
HDR format                               : Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU, HDR10 compatible / SMPTE ST 2086, HDR10 compatible
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 50 min 19 s
Bit rate                                 : 15.4 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 24.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.077
Stream size                              : 5.41 GiB (93%)
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : BT.2020
Mastering display luminance              : min: 0.0000 cd/m2, max: 1000 cd/m2

Dopesick S01 2160p HULU WEB-DL DDP 5.1 DV HEVC-FLUX
`Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@Main
HDR format                               : Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU, HDR10 compatible / SMPTE ST 2094 App 4, Version 1, HDR10+ Profile B compatible
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 1 h 2 min
Bit rate                                 : 7 068 kb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 24.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.036
Stream size                              : 3.08 GiB (96%)
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0001 cd/m2, max: 1000 cd/m2
Maximum Content Light Level              : 1043 cd/m2
Maximum Frame-Average Light Level        : 197 cd/m2`

**Comment by nismanoku** [comment]
For now added two extra lines to preferred;

The one you add to must not contain in the guide with score -300
`/\b(?=.*(dv|dovi|dolby[ .]vision)\b)(?=.*(WEB[-_. ]DL|WEBDL|AmazonHD|iTunesHD|MaxdomeHD|NetflixU?HD|WebHD|[. ]WEB[. ](?:[xh]26[45]|DDP?5[. ]1)|[. ](?-i:WEB)$|\d+0p(?:[-. ]AMZN)?[-. ]WEB[-. ]|WEB-DLMux|\b\s\/\sWEB\s\/\s\b|AMZN[. ]WEB[. ]|WebRip|Web-Rip|WEBMux))/i`

One new line with score 320
`/\b(?=.*(dovi[ .]hdr|dv[ .]hdr|hdr[ .]dv|hdr[ .]dovi)\b)/ix`

This gives the release with only DV a negative score and is not picked up. The caveat is that when nothing better is found it will still download the dv only release. Don't know if there is a option to disregard dv only but allow when dovi (dv) and hdr (hdr10) in the title

**Comment by TRaSH-** [comment]
This will be covered with #452, once it's merged

**Comment by TRaSH-** [comment]
Fixed: #452
