### ISSUE TITLE
[Bug] BR-Disk not matching

### ISSUE THREAD

**Issue by tordenflesk** [TRaSH-/Guides#411]
**Which Guide**
Collection of Custom Formats

**Describe the Error in the Guide**
the BR-Disk custom format doesn't match / block the following release:
The Fifth Element 1997 Blu-ray UHD HDR Disc TrueHD 7.1 -HDRINVASION

**Expected behavior**

**Screenshots**
https://i.imgur.com/VNvlUxR.png

**Additional context**

**Comment by TRaSH-** [comment]
@ItsME6969 could you take a look ?

**Comment by TRaSH-** [comment]
Should be fixed with PR #413
