### ISSUE TITLE
[REQUEST] radarr custom formats

### ISSUE THREAD

**Issue by Drapersniper** [TRaSH-/Guides#439]
**For which application would like to see this Guide ?**
Radarr

**Describe what you would like to see in the Tutorial/Guide**

it would be nice if you could put together a guide to import the radarr custom formats in one go.

For example using the radarr api to add/update the profiles with the latest ones avaliable.

The way I gone about doing this is cloning the repo then iterating through the json folder and making an api call for each file but a method that doesn't require the cloning would be awesome.

**Comment by TRaSH-** [comment]
That already exist
- It's possible with [Notifiarr](https://notifiarr.com/profile.php)
- It's possible with [trash-updater](https://github.com/rcdailey/trash-updater)

Any other questions about it you can ask in our Discord Support Channel
