### ISSUE TITLE
[REQUEST] Update Radarr Guides with new Import functionality for existing CFs

### ISSUE THREAD

**Issue by bakerboy448** [TRaSH-/Guides#440]
**For which application would like to see this Guide ?**

Radarr

**Describe what you would like to see in the Tutorial/Guide**

Add details for importing existing
https://github.com/Radarr/Radarr/commit/eecd4e4b7d21c5fa70181fd87f6edd5d624924ff

![image](https://user-images.githubusercontent.com/55419169/147020892-4ad11541-1841-4abf-b11e-29ee6b180aba.png)
![image](https://user-images.githubusercontent.com/55419169/147020932-edb0bd7d-46ee-4fab-b594-b1b996250be5.png)

**Comment by TRaSH-** [comment]
Hm,
Think the how to import custom formats would be the best place to add it ?

**Comment by bakerboy448** [comment]
Yeah I think so

**Comment by TRaSH-** [comment]
it's already gone from my changelog history of Radarr, but do you know from which Radarr version this is possible ?

**Comment by TRaSH-** [comment]
found it with the help of @ta264 
https://dev.azure.com/Radarr/Radarr/_build/results?buildId=4210&view=results

**Comment by TRaSH-** [comment]
Done with #445 in a own guide (This includes also links to the automation applications)
