### ISSUE TITLE
[REQUEST] How to update custom formats with changes on GitHub

### ISSUE THREAD

**Issue by briandipalma** [TRaSH-/Guides#443]
**For which application would like to see this Guide ?**
Radarr

**Describe what you would like to see in the Tutorial/Guide**
At the moment I'm having to delete a custom format and re-add it, which involves resetting a custom format score in the profiles. Although I guess this isn't something that Radarr supports? Editing the custom formats should allow you to paste in the new text and it should override the previous value without losing the scores.

Actually was thinking of raising an issue in the Radarr repo about this configuration approach. To my mind it should just be a directory that Radar reads with a bunch of text files in it with all my configuration changes, it's then trivial to update/backup/store in a git repo etc.
It seems that at the moment we have a binary SQL database which needs zipping up and backing up somewhere.

**Comment by TRaSH-** [comment]
Well I got good news for you then.

That already exist
- It's possible with [Notifiarr](https://notifiarr.com/profile.php)
- It's possible with [trash-updater](https://github.com/rcdailey/trash-updater)

Any other questions about it you can ask in our Discord Support Channel

And your other question seems to have been merged in to Radarr nightly.
#440

**Comment by TRaSH-** [comment]
Done with #445 in a own guide (This includes also links to the automation applications)
