### ISSUE TITLE
Improvement: Correct identification of IMAX enhanced

### ISSUE THREAD

**Issue by michpas** [TRaSH-/Guides#446]
Identification of IMAX Enhanced format

**Describe the Error in the Guide**
Since 19th Nov Disney+ streams IMAX Enhanced. 
[https://help.disneyplus.com/csp?id=csp_article_content&sys_kb_id=ae2b1af1dbab30981830269ed3961944](url)
[https://www.techradar.com/news/disney-plus-will-offer-imax-versions-of-marvel-films-including-shang-chi](url)
[https://www.howtogeek.com/769609/what-is-imax-enhanced/](url)
It seems only disneyPlus is offering this IMAX Enhanced format that is compatible with all players.

At this moment only the following movies:
Ant-Man and the Wasp, Avengers: Infinity WarAvengers: Endgame, Black Panther,  Black Widow, Captain America: Civil War,Captain Marvel,Doctor Strange,Guardians of the Galaxy 1 & 2,Iron Man,Thor Ragnarok,Shang-Chi and the Legend of the Ten Rings
--
Currently the custom formats only identify IMAX, which often is not the IMAX enhanced.

**Expected behavior**
A custom fornat with a difference between IMAX and IMAX Enhanced.

**Additional context**
Looking at the titles it seems when both the word IMAX and DSNP is included it's IMAX Enhanced.

**Comment by TRaSH-** [comment]
So only Disney WEB-DL releases imax enchanted ?

Would need to check if they also use the enchanted versions in a hybrid release.

**Comment by michpas** [comment]
yeah. seems to be streaming format only. I guess Web-DL. Definately, not on blu-ray discs

**Comment by TRaSH-** [comment]
Do you only do WEB-DL or also Blu-ray encodes or remuxes

**Comment by michpas** [comment]
I do all three. I guess in the configuration of Radarr/Sonarr now I have a
challenge. Either bucket them all three into one or make WebDL higher than
4K

**Comment by TRaSH-** [comment]
What could result in to getting lower quality video and audio if not using more custom formats

**Comment by TRaSH-** [comment]
doing some little more research on it, but aren't basically till now all web-dl with imax from disney ?
hmm found the imax core are those imax enchanted ?

**Comment by michpas** [comment]
I found the following two files; which are WEBDL and have the word IMAX; but these are not IMAX Enhanced.

- Natale.A.8.Bit.2021.iTA-ENG.iMAX.WEBDL.1080p.x264-CYBER.mkv
- Wonder.Woman.1984.2020.iTA-ENG.iMAX.WEBDL.AMZ.2160p.x265-CYBER.mkv
- Mission.Impossible.Fallout.2018.1080p.IMAX.WEB-DL.DD5.1.H264-FGT

Till date I think indeed only DisneyPlus in Imax offers this new IMAX format

**Comment by TRaSH-** [comment]
Did some research and it seems that Bravia core also have IMAX enchanted.
https://www.imaxenhanced.com/

**Comment by TRaSH-** [comment]
Are all Disney+ with IMAX, IMAX Enhanced ?

**Comment by MylesLandais** [comment]
`Avengers.Endgame.2019.IMAX.2160p.DSNP.WEB-DL.HDR.DDP5.1.Atmos.H.265-ABBiE`

IMAX.2160p.DSNP might work if that assumption is true.

**Comment by TRaSH-** [comment]
I already have a working Custom Format for it, It's been tested at the moment by a few Discord users in the special  test channel,
But wanted to be sure that all imax from disney+ are  IMAX Enhanced.
If you're interested you can join my discord server and request access.

**Comment by TRaSH-** [comment]
Fixed with #468
