### ISSUE TITLE
[REQUEST] - Sonarr and Radarr Merge all Qualities & Handle via Preferred Words / Custom Formats

### ISSUE THREAD

**Issue by bakerboy448** [TRaSH-/Guides#449]
**For which application would like to see this Guide ?**
Sonarr and Radarr

**Describe what you would like to see in the Tutorial/Guide**

Users often wish to prefer h265 over h264 and yet still prefer 1080p over 720p.

However they prefer encoding over quality.

Add a guide that details merging all qualities and then using preferred words to identify and order qualities and encodings

This should also be done for Radarr but with Custom Formats

**Comment by TRaSH-** [comment]
hmm something like i use for the radarr special quality profiles (that i don't share on the guides and only for people that are really interested in them) where i put the remuxes and bluray together.
and where the custom formats trumps quality source

**Comment by TRaSH-** [comment]
Done with #482
