### ISSUE TITLE
[Bug] Revision time is last commit

### ISSUE THREAD

**Issue by patrick-5546** [TRaSH-/Guides#454]
**Describe the Error**
Currently the revision time for every page is the time of the most recent commit to the master branch.

**Expected behavior**
Revision time for every page is what it is supposed to be.

**Solution**
When checking out the code in the deploy workflow, set `fetch-depth` to `0`.

Example:

https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/blob/ccf498bab42e085b7190eed4a0aa48c4c807e3a0/.github/workflows/pythonpublish.yml#L11-L13

   - Note that it should be `fetch-depth` and not `fetch_depth`; `fetch_depth` gives a warning: https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/actions/runs/1579704317

**Resources**
- https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/index.html#note-when-using-build-environments

**Comment by TRaSH-** [comment]
I'll take a look,
But I did a few days a go I did  change that almost hit all pages

**Comment by patrick-5546** [comment]
The latest commit at December 29, 2021 at 06:15:01 UTC only modifies Guides/docs/Sonarr/Sonarr-Release-Profile-RegEx.md, but every single page has a revision date of  December 29, 2021 at 06:15:01. This is because the checkout action grabs the latest commit (`fetch-depth` is 1) by default
