### ISSUE TITLE
[Bug] - Add Sonarr Season Pack Warning

### ISSUE THREAD

**Issue by bakerboy448** [TRaSH-/Guides#474]
**Which Guide**
Sonarr

**Describe the Error in the Guide**
https://discord.com/channels/383686866005917708/383687854057979906/932796301370880040

> not sure if you'd call it a bug-ish or a feature request
> 
> `/\bS\d+\b(?!E\d+\b)/i`  season packs are preferred; however, given the folder name is ignored the error/warning/issue occurs as the file names would not be a season pack of course.
> 
> keep in mind this is the only way to prefer season packs if you have preferred words due to the long standing bug.
> > Preferred Words overrule season pack preference
> <https://github.com/Sonarr/Sonarr/issues/3562>

**Expected behavior**
add warning about season pack upgrades/loops

**Screenshots**
![image](https://user-images.githubusercontent.com/55419169/149851661-3150f1e5-50b9-4acf-9e5b-83138deaf245.png)

**Additional context**
above

**Comment by TRaSH-** [comment]
Fixed with #477
