### ISSUE TITLE
[FEEDBACK] Netflix Web-DL/RIP incorrect

### ISSUE THREAD

**Issue by g4m3r7ag** [TRaSH-/Guides#49]
I believe 

/(nf|netflix).?(dl|rip)/i

should be 

/(nf|netflix).?web.?(dl|rip)/i

As it's not adding the preferred words into the file name without the "web.?"

**Comment by nemchik** [comment]
is `web` meant to be optional or required?

**Comment by TRaSH-** [comment]
Thnx Fixed in #50

**Comment by TRaSH-** [comment]
> is `web` meant to be optional or required?

required
