### ISSUE TITLE
[Bug] RADARR LQ GROUP

### ISSUE THREAD

**Issue by bakerboy448** [TRaSH-/Guides#510]
**Which Guide**
Please add which Guide you found a Bug/Error with.
Radarr
**Describe the Error in the Guide**

block ``The.Last.Blockbuster.2020.1080p.BD.AVC.DD2.0-Liber8``  it's BR-DISK that's poorly labeled.

**Expected behavior**

Above

**Screenshots**

**Additional context**

**Comment by TRaSH-** [comment]
thnx
Fixed with #511
