### ISSUE TITLE
[FEEDBACK] New 720/1080 h265 regex

### ISSUE THREAD

**Issue by g4m3r7ag** [TRaSH-/Guides#52]
The new regex for blocking h265 releases (/(?=(1080|720)).*((x|h)265|hevc)/i) isn't blocking releases that have it named "1080p.AMZN.WEB-DL.DD5.1.H.265-SiGMA" I assume because of the period between H and 265. I don't know enough about RegEx to know how to correct it unfortunately.

**Comment by TRaSH-** [comment]
Thnx, seems I didn't notice it during my check,
Kinda weird being I did it with the Radarr CF.
But it's fixed with #54
