### ISSUE TITLE
[Bug] No-RlsGroup is too agressive.

### ISSUE THREAD

**Issue by nickavem** [TRaSH-/Guides#583]
**Which Guide**
Radarr

**Describe the Error in the Guide**
The "No-RlsGroup" format will often exclude releases from indexers who use spaces in their formatting.

**Expected behavior**
Keep these releases.

**Screenshots**
![Screenshot from 2022-05-10 15-45-03](https://user-images.githubusercontent.com/72708798/167709835-1e4708e7-17e6-420b-ae5f-55a01b122823.png)

![Screenshot from 2022-05-10 15-45-22](https://user-images.githubusercontent.com/72708798/167709876-ae76091c-1838-4a0c-8757-a37da435b9b5.png)

Same releases, but one is marked as not having a release group.

**Comment by bakerboy448** [comment]
not a guide issue; those do not have a group.

https://github.com/Prowlarr/Indexers/issues/156
