### ISSUE TITLE
[Bug] Release Profile RegEx (Anime): Typo in Folder Naming Scheme 

### ISSUE THREAD

**Issue by CaTeNdrE** [TRaSH-/Guides#624]
**Which Guide**
[Sonarr-Release-Profile-RegEx-Anime.md](https://github.com/TRaSH-/Guides/blob/master/docs/Sonarr/Sonarr-Release-Profile-RegEx-Anime.md)

**Describe the Error in the Guide**
In the section [Suggested naming scheme](https://github.com/TRaSH-/Guides/blob/master/docs/Sonarr/Sonarr-Release-Profile-RegEx-Anime.md#suggested-naming-scheme), the [Series Folder Format](https://github.com/TRaSH-/Guides/blob/master/docs/Sonarr/Sonarr-Release-Profile-RegEx-Anime.md#series-folder-format) has a typo in the suggested naming scheme: **"{Series TitleTheYear} [tvdb-{TvdbId}]"**. This will not produce the sample title "The Series Title! (2010) [tvdb-12345]" but rather "Series Title!, The (2010) [tvdb-12345]"

**Expected behavior**
The suggested naming scheme for the [Series Folder Format](https://github.com/TRaSH-/Guides/blob/master/docs/Sonarr/Sonarr-Release-Profile-RegEx-Anime.md#series-folder-format) should be **"{Series TitleYear} [tvdb-{TvdbId}]"**

**Screenshots**
<img width="456" alt="seriestitle" src="https://user-images.githubusercontent.com/41076588/172923054-dacacfb9-d0a3-4283-8d40-522c756a80af.png">
**vs.**
<img width="456" alt="seriestitle2" src="https://user-images.githubusercontent.com/41076588/172923106-5a7df7b6-dbbc-4c09-8793-0195d9d22963.png">

**Comment by TRaSH-** [comment]
i'll take a look at it tomorrow, and try to fix asap

**Comment by TRaSH-** [comment]
fixed with #639
