### ISSUE TITLE
[Bug] Sonarr Optional Bad Audio -25 too low

### ISSUE THREAD

**Issue by bakerboy448** [TRaSH-/Guides#699]
**Which Guide**

Sonarr Release Profiles
- optional No Dual Audio Groups failed to block the groups as -25 is too low of a negation

**Describe the Error in the Guide**

```
Name
South.Park.S02.1080p.AMZN.WEB-DL.DDP2.0.H.264.DUAL-RiPER
Indexer
UseNetIndexer (Prowlarr)
Release Group
RiPER
Preferred Word Score
+110
```

**Expected behavior**

Release should not have downloaded as it is an unwanted dual audio group

**Screenshots**

N/A

**Additional context**

N/A

**Comment by TRaSH-** [comment]
it shouldn't be in -25 in the first place
![image](https://user-images.githubusercontent.com/6155095/183298937-30619a6d-5844-47b1-a147-65a70de11ffa.png)

so i think i screwed up in the json, or it got screwed up after a PR

**Comment by bakerboy448** [comment]
https://github.com/TRaSH-/Guides/blob/master/docs/json/sonarr/optionals.json

Json is good. Either user or notifiarr issue
