### ISSUE TITLE
Help with CF scores

### ISSUE THREAD

**Issue by kevindd992002** [TRaSH-/Guides#76]
So I'm still trying to wrap my head around your guide but I'm not a 100% clear on how the best way to use scores for the different CF's is. Like what you put as an example in your guide, I do want to implement the audio format order that you have there except I don't want FLAC, PCM, MP3, and OPUS.

![image](https://user-images.githubusercontent.com/3907957/103366402-88f6f780-4afd-11eb-9923-053ba9c2bfd7.png)

My goal is to have the best 2160p release, of course. When I say best, my end target is TrueHD ATMOS plus Dolby Vision. I prefer DV vs. HDR10/HDR as my TV supports it. So my preference is a mix of both audio and video. I don't care about number of channels for now because higher channels almost always come with the higher quality audio formats anyway.

I'm setting up the hierarchy now based on what you said here:

![image](https://user-images.githubusercontent.com/3907957/103366549-e8ed9e00-4afd-11eb-9159-1f9049f71383.png)

But I'm not confident in what I did and I can't, for the love of God, figure this out. Here's what I have:

![image](https://user-images.githubusercontent.com/3907957/103366618-133f5b80-4afe-11eb-910e-9ec4ca1623c5.png)
![image](https://user-images.githubusercontent.com/3907957/103366637-1c302d00-4afe-11eb-986f-bbfceb371556.png)
![image](https://user-images.githubusercontent.com/3907957/103366657-25b99500-4afe-11eb-9177-f8b4bcee0803.png)

What is your suggestion with my scores? And as for the Upgrade Until CF Score value, would making it equal to the sum of all positive CF scores be wise?

**Comment by TRaSH-** [comment]
It would be much easier if you would join my discord server being I or others are able to provide live support.

In your case the main used profile is also important so i suggest that you check remuxes
