### ISSUE TITLE
[Bug] Regex issue with Sonarr Optional - Dislike release containing: 1-

### ISSUE THREAD

**Issue by mynameisbogdan** [TRaSH-/Guides#802]
**Which Guide**
Sonarr Optional - Dislike release containing: 1-

**Describe the Error in the Guide**
Seems like `/(1-.+)$/i` matches `The.Sopranos.S02.1080p.WEB-DL.h.264.DD5.1-NTb`, and I think this matches a lot of other releases giving them a score of `-25`.

![Screenshot](https://user-images.githubusercontent.com/707714/189525993-7d67a225-ff9b-41e0-aded-94786b60941a.jpg)

**Comment by TRaSH-** [comment]
yeah bad naming on their end
being the season pack is called officially `The.Sopranos.S02.1080p.WEB-DL.DD5.1.H.264-NTb`, what wouldn't give any issues and is a proper way of naming.
and with the episodes they screwed up and named it `The.Sopranos.S02Exx.1080p.WEB DL.h.264.DD5.1 NTb.mkv`
My suggestion would be don't use the optional regex, the regex was made for usenet and especially when you use a naming scheme `{Original Title}`.

**Comment by mynameisbogdan** [comment]
Okay then, I'll ignore that rule.
