### ISSUE TITLE
SiGLA

### ISSUE THREAD

**Issue by KnifeFed** [TRaSH-/Guides#805]
I'm wondering about these inclusions: https://github.com/TRaSH-/Guides/blob/9f995c58e314be08f3dfbecd85a87a6c1222ad31/docs/json/sonarr/cf/bad-dual-groups.json#L134
https://github.com/TRaSH-/Guides/blob/9f995c58e314be08f3dfbecd85a87a6c1222ad31/docs/json/radarr/cf/bad-dual-groups.json#L134
I had not heard of them before but they recently released `Solar.Opposites.S03.1080p.DSNP.WEB-DL.DDP5.1.H.264-SiGLA` which trumped the NTb release on e.g. HDB/BHD.

**Comment by bakerboy448** [comment]
They take existing releases and remux them to make a foreign audio the primary track
