### ISSUE TITLE
[Suggestion] Remove V3 node from Radarr page now that its the only supported version.

### ISSUE THREAD

**Issue by rcdailey** [TRaSH-/Guides#84]
It's a bit unnecessary to have to expand "V3" to see the Radarr guides now that v2 support has been dropped. The guides should be all at the root level now and clickable without expanding a tree node first.

**Comment by TRaSH-** [comment]
That's true and I was looking at it last weekend,
but if I change it we will break all direct links to it,
and when Radarr decides to start with Radarr v4 it would mean I need to move it again.
I will take a look if I'm able to set it to auto expand for only this page but I'm not sure if that's possible.

**Comment by rcdailey** [comment]
Perhaps a more modular approach would be a dedicated page for each version of Radarr. How you want to structure the links to those pages is up for debate, but I'd likely go with a navigation tree on the main page, something like:

```
Radarr
     -> V4
     -> V5
(etc)
```

**Comment by TRaSH-** [comment]
![image](https://user-images.githubusercontent.com/6155095/103681000-3ac37780-4f87-11eb-9236-f242c728c510.png)

these are the main entries to the guides for a specific application
and the navigation on the left are the sub sections
So adding a v2/v3 to the top is one big mess

Example how Sonarr looks

![image](https://user-images.githubusercontent.com/6155095/103681267-8a09a800-4f87-11eb-921e-931b4f1a203e.png)

**Comment by rcdailey** [comment]
To better show what I'm suggesting, an alternative would be a hover submenu that pops up on the main menu that allows you to navigate to a specific version. Steps:

1. Hover mouse cursor over "Radarr" on the main menu
2. A submenu appears with "V2" and "V3" under it
3. Click one of the versions to be taken to the Radarr page for that version, with a tree view on the left (as it is today) but without the collapsing sections, making it more navigation friendly and straightforward.

The benefit to this is that when a new version is released, you don't have to go change existing pages, you just add a new one. It makes it easier to maintain.

**Comment by TRaSH-** [comment]
```
The benefit to this is that when a new version is released, you don't have to go change existing pages, you just add a new one. It makes it easier to maintain.
```
I don't need to change anything on the existing page,
i just create a new folder and start adding the new guides to it and it's automatically created.

Keep in mind the Guide site makes use of mkdocs,
I can only use plugins/add-ons what exists for it.

So if you find one tell me and i can check if i can add it.
I'm not going to search for something like that active, I better waste my time creating more "needed" guides. ;)
You can re-open it when you found one.

**Comment by rcdailey** [comment]
As a compromise, would it be reasonable (or even doable) to have the latest version in the tree expanded by default?

**Comment by TRaSH-** [comment]
That isn't possible it's all or nothing,
i already asked => https://github.com/squidfunk/mkdocs-material/discussions/2185
