### ISSUE TITLE
[Bug] Extra space in the Radarr recommended naming scheme

### ISSUE THREAD

**Issue by Nastym** [TRaSH-/Guides#864]
**Which Guide**
Radarr

**Describe the Error in the Guide**
There's an extra space in the Radarr recommended naming scheme:  { Mediainfo AudioChannels}   <-- you can see a space before the M

**Expected behavior**
Having a space there messes up Plex's scanning.  You end up getting weird  {[1080  looking texts in the movie screen.

**Screenshots**

**Additional context**

**Comment by owine** [comment]
This is a red herring. That space is needed to put a space between the codec and channel count. What you are seeing is probably related to editions.

**Comment by bakerboy448** [comment]
The space is intentional.

The second issue is due to using an outdated version of radarr and the new naming scheme for 4.2.4 which removes {edition-} if there is no edition.  Upgrade radarr and have it re-rename your files.  Failure to do so results in {edition-} and weird plex behavior
