### ISSUE TITLE
[Bug] Regex is too aggressive in "Dislike release containing: 1-"

### ISSUE THREAD

**Issue by melwil** [TRaSH-/Guides#909]
**Which Guide**
Sonarr - Optional - Dislike release containing: 1-

**Describe the Error in the Guide**
The regex is too general, and catches a lot of releaases on the format `<surround quality>-<release group>`

**Expected behavior**
I would expect that it can distinguish between a surround format and a random prefix for a string

**Screenshots**
<img width="777" alt="image" src="https://user-images.githubusercontent.com/632466/196705496-1de00a23-f52b-4956-a57f-983dfe9bf323.png">

**Additional context**
None

**Proposed solution**
I have expanded the regex to be a little smarter, and verified that it works for me.  
Replacing `/(1-.+)$/i`
With `/(?<!\d\.)(1-.+)$/i`

Can be tested here: https://regex101.com/r/T8h2ER/1

**Comment by TRaSH-** [comment]
It's a optional for a reason
If it doesn't fit your needs then don't use the specific optional
I personally don't even use it.

**Comment by melwil** [comment]
I get that, but it's still wrong in most cases. The change makes it work more like intended. Optional or no.

**Comment by TRaSH-** [comment]
Oh you made a charge
Didn't see it on my stupid phone.
Let me take a look when I get home
Thnx appreciate it
