### ISSUE TITLE
Scoring issue with FraMeSToR and HDR formats

### ISSUE THREAD

**Issue by jyggen** [TRaSH-/Guides#91]
The Radarr guide currently suggests, for good reason, to use `HDR` and `FraMeSToR` with equal score since FraMeSToR don't include HDR in their release names. Once a FraMeSToR release is on disk however, a scoring issue occurs. Oh no!

Since Radarr also detects custom formats based on filename, and the recommended naming scheme adds HDR to it, both the `HDR` and the `FraMeSToR` formats will match the file once its renamed. This results in the release suddenly having a higher score compared to when it was first downloaded. 

I'm not entirely sure how to fix it. The main problem is that FraMeSToR releases aren't always in HDR, otherwise it would be as easy as adding the FraMeSToR regex to the `HDR` format. 

Another option is to add a negating HDR regex to the `FraMeSToR` format. This won't prevent anything from being downloaded (since FraMeSToR never includes HDR in their release names anyway), but it will prevent a file on disk from matching both `HDR` and `FraMeSToR`. If the release isn't in HDR however, the `FraMeSToR` format will sadly still be applied and give it a "HDR-like score". Not to mention that this prevents FraMeSToR's actual HDR releases on disk from matching the `FraMeSToR` format - which makes the format a bit of a lie.

The third option that comes to mind is to add a new `HDR (indeterminate)` format that is more or less option 2 but with another name. In similar fashion to how there's the `ATMOS (indeterminate)` format to leave proper detection to the filename matching, this format could mark all FraMeSToR releases (and other groups in the future) as _potential_ HDR releases. It still has the same problem as option 2 though, namely that if it turns out to _not_ be in HDR it will still get the extra score from `HDR (indeterminate)`.

This seems to be the recurring theme here. How do you handle and score something that _could_ be what you want? Something to figure out, or maybe it's just not worth the hassle :)

**Comment by bakerboy448** [comment]
Add an exclude to Framestor’s format if it already has HDR would probably work

**Comment by jyggen** [comment]
I wrote a quick data analysis script using HDB's API since they, as of recently, tag HDR releases. Out of all the available FraMeSToR releases, _zero_ 1080p releases are in HDR. With the exception of _two_ releases, all 2160p releases are in HDR _unless_ they have `SDR` or `DoVi`  in the name.

So making the `FraMeSToR` format 2160p only, adding a negating HDR regex (so it won't match it on disk), as well as adding negating SDR and DoVi regexes will make it _almost_ guaranteed to be a HDR release (in 267 out of 269 cases).

**Comment by TRaSH-** [comment]
```
I'm not entirely sure how to fix it. The main problem is that FraMeSToR releases aren't always in HDR, otherwise it would be as easy as adding the FraMeSToR regex to the HDR format.
```
I think 99% of the 4k releases of framestor are HDR except the 1080p ones.

HDR is a 4k thing and only those weird 1080p releases do 1080p HDR,
and those should be only used when you actually got a 4k TV and not a non 4k tv.
In my opinion they should be completely ignored in the first place and they probably will if you use my so called Golden Rule regex (ignore x265 releases in 720/1080p).

But I'm open for any workable PR for this issue ;)

**Comment by TRaSH-** [comment]
Fixed and will be merged soon with the next update
