### ISSUE TITLE
[REQUEST] AV1 Ignore

### ISSUE THREAD

**Issue by shadofall** [TRaSH-/Guides#928]
**For which application would like to see this Guide ?**
Radarr / Sonarr 

Starting to see more AV1 encodes pop up., might be a good idea to add a regex to ignore AV1 since not all  Players/Hardware support it well yet.

**Comment by TRaSH-** [comment]
Import the following JSON in to Radarr and give it a score of -10000

```json
{
  "name": "AV1",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "AV1",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "\\bAV1\\b"
      }
    }
  ]
}
```

**Comment by shadofall** [comment]
Thanks. that works well enough for Radarr. but what about Sonarr. since Sonarr hasn't introduced custom formats
Not sure if i should try to append it to the golden rule  or create a separate entry. not particularly good at regex

**Comment by TRaSH-** [comment]
for Sonar v3 you can use 
```
/\bAV1\b/i
```
with a score of -10000
