### ISSUE TITLE
[Bug] Sonarr optional "Ignore AV1" formatting is wrong

### ISSUE THREAD

**Issue by allquiet-hub** [TRaSH-/Guides#968]
**Which Guide**
Please add which Guide you found a Bug/Error with.
https://github.com/TRaSH-/Guides/blob/91988c93f0f0f1b5509b7c48a304e5d6dbcdfc15/docs/json/sonarr/rp/optionals.json

**Describe the Error in the Guide**
```
    "name": "Ignore AV1",
    "trash_id": "4861d8238f9234606df6721df6e27deb",
    "term": "/\bAV1\b/i"
```
has the end result of 

![image](https://user-images.githubusercontent.com/14953166/201528476-72de0ff4-5e8d-4cbb-a4e9-f8af2a5f3056.png)
![image](https://user-images.githubusercontent.com/14953166/201528491-9e688d89-73b4-46c0-a12e-c7b0512432f6.png)

The correct term is:
```
    "term": "/\\bAV1\\b/i"
```

like in the other terms. Which results in this:

![image](https://user-images.githubusercontent.com/14953166/201528592-fbf1cf88-a171-4a4f-9fff-171a92da02de.png)

**Comment by TRaSH-** [comment]
Thnx,
Are you able to create a PR for it ?
Else i need to ask someone else to take a look at it.
I'm busy with another project at the moment
