### ISSUE TITLE
Priority Issue with Special Edition matching

### ISSUE THREAD

**Issue by Davst** [TRaSH-/Guides#984]
Following your great configuration settings I have an issue with the following situation

**Movie.2019.1080p.BluRay.REMUX.Criterion.Collection.Black.and.White.Version.AVC.TrueHD.Atmos.7.1-MrTentsaw**
Tags (TrueHD ATMOS) (7.1 Surround) (Criterion Collection) (Special Edition)
Score: 5150

**Movie.2019.1080p.BluRay.REMUX.Criterion.Collection.AVC.TrueHD.Atmos.7.1-MrTentsaw**
Tags (TrueHD ATMOS) (7.1 Surround) (Criterion Collection)
Score: 5025

This listing also had one release called Movie.2019.BW.720p.BluRay.x264-REGRET

I would rather not have the color movie replaced by a black and white version.

**Comment by Davst** [comment]
For anyone finding this, temp fixed by adding the following rule block to the Special Edition set

Negated

`black.(and|n).white`

**Comment by TRaSH-** [comment]
The replacing wouldn't happen
Being quality trumps all and a remux trumps a 720p Blu-ray
Will take a look at the special edition and cc edition
Thnx

**Comment by Davst** [comment]
> Being quality trumps all and a remux trumps a 720p Blu-ray

Yeah just added that as another example of naming for black and white that turned up in my results.

**Comment by yammes08** [comment]
After doing some testing on this, the only real solution is to create a personal blocklist that contains any black and white movie's own specialised naming that you come across. To me this would seem out of scope for the more generalised nature of the CFs in Trash's guide, and would be best handled individually according to personal preference.

**Comment by TRaSH-** [comment]
Because you got so many variables with Special Editions it's a never ending story if we need to maintain this
And to make it even worse
Not all Special Editions are better then Edition x
It depends per movie, So with this conclusion I think we can close this issue.
