### ISSUE TITLE
Movie with "Special" in the title is matching on the "Special Edition" Quality 

### ISSUE THREAD

**Issue by dreondre** [TRaSH-/Guides#988]
It looks as though the Special Edition quality profile regex is matching on movie titles where there's the word "Special" in the title.
I believe it's because the words special and edition are separated by an OR. 
For example, around this time of year, anything with "Holiday Special" in the title will match. 
Is it possible to put "special" and "edition" together?

**Comment by bakerboy448** [comment]
Not a trash CF issue. It's a radarr bug
https://github.com/Radarr/Radarr/issues/7004

**Comment by dreondre** [comment]
Sounds good, thanks for looking out.
